insert into estación (nombre, direccion) values ('Nikolaus and Sons', '06173 Fuller Lane');
insert into estación (nombre, direccion) values ('Schuster Group', '99 Mandrake Plaza');
insert into estación (nombre, direccion) values ('Mayert, Stiedemann and Parisian', '937 Utah Circle');
insert into estación (nombre, direccion) values ('Balistreri, Kunde and Muller', '08454 Nevada Road');
insert into estación (nombre, direccion) values ('Keebler, Bednar and Hettinger', '72 Debra Crossing');
insert into estación (nombre, direccion) values ('Crooks, Durgan and Flatley', '22 Scofield Avenue');
insert into estación (nombre, direccion) values ('Tremblay-Glover', '8 Harbort Avenue');
insert into estación (nombre, direccion) values ('Ankunding and Sons', '6536 Farmco Junction');
insert into estación (nombre, direccion) values ('Purdy Inc', '67 Muir Park');
insert into estación (nombre, direccion) values ('Skiles Group', '89191 Wayridge Way');
insert into estación (nombre, direccion) values ('Lueilwitz-McLaughlin', '05 Reindahl Pass');
insert into estación (nombre, direccion) values ('Jacobson and Sons', '22194 Schmedeman Parkway');
insert into estación (nombre, direccion) values ('Koch and Sons', '878 Mcguire Terrace');
insert into estación (nombre, direccion) values ('Ritchie, Weber and Johnston', '2 Myrtle Court');
insert into estación (nombre, direccion) values ('Boyer-Lueilwitz', '07373 Sundown Street');
insert into estación (nombre, direccion) values ('Balistreri-Harber', '882 Coleman Junction');
insert into estación (nombre, direccion) values ('Dickens-Padberg', '7 Grover Crossing');
insert into estación (nombre, direccion) values ('Mann and Sons', '29127 Bayside Center');
insert into estación (nombre, direccion) values ('Nienow Inc', '5 Express Pass');
insert into estación (nombre, direccion) values ('Murray, Kshlerin and Ebert', '30366 Corry Center');
insert into estación (nombre, direccion) values ('Lowe Inc', '33 Oriole Way');
insert into estación (nombre, direccion) values ('Hoppe-Kassulke', '2 Sloan Lane');
insert into estación (nombre, direccion) values ('Hayes, Wuckert and Sauer', '92 Pepper Wood Alley');
insert into estación (nombre, direccion) values ('Williamson-Crist', '68591 Warrior Way');
insert into estación (nombre, direccion) values ('Bailey-Barton', '53868 Amoth Street');
insert into estación (nombre, direccion) values ('Nienow, Breitenberg and Will', '659 Esch Circle');
insert into estación (nombre, direccion) values ('Keeling-Cremin', '13379 Sunbrook Lane');
insert into estación (nombre, direccion) values ('Carter and Sons', '849 Homewood Court');
insert into estación (nombre, direccion) values ('Schneider-Boehm', '2417 Autumn Leaf Point');
insert into estación (nombre, direccion) values ('Dibbert-Cormier', '5 Maple Junction');
insert into estación (nombre, direccion) values ('Miller-Bayer', '59889 Onsgard Street');
insert into estación (nombre, direccion) values ('Cummerata and Sons', '85 Knutson Hill');
insert into estación (nombre, direccion) values ('Thiel Group', '2 Eastwood Circle');
insert into estación (nombre, direccion) values ('Gerhold, Smith and Bechtelar', '8 Prentice Trail');
insert into estación (nombre, direccion) values ('Jacobi-Miller', '5534 Banding Street');
insert into estación (nombre, direccion) values ('Rosenbaum LLC', '7893 Lighthouse Bay Trail');
insert into estación (nombre, direccion) values ('Hagenes-Gulgowski', '491 Annamark Court');
insert into estación (nombre, direccion) values ('Wiegand, Sipes and Stokes', '9697 Muir Hill');
insert into estación (nombre, direccion) values ('Adams LLC', '2661 Maple Center');
insert into estación (nombre, direccion) values ('Yundt-Bogan', '0 Grayhawk Lane');
insert into estación (nombre, direccion) values ('O''Hara LLC', '682 Vidon Pass');
insert into estación (nombre, direccion) values ('Quigley-Hansen', '1030 Montana Point');
insert into estación (nombre, direccion) values ('Renner, Sanford and Howell', '1263 Muir Point');
insert into estación (nombre, direccion) values ('Waelchi, Haley and Ortiz', '7202 Prairie Rose Parkway');
insert into estación (nombre, direccion) values ('VonRueden-Adams', '8 Schmedeman Pass');
insert into estación (nombre, direccion) values ('Simonis LLC', '9355 Rieder Court');
insert into estación (nombre, direccion) values ('Emmerich LLC', '3633 Clarendon Hill');
insert into estación (nombre, direccion) values ('Quigley-Nitzsche', '55999 Westridge Avenue');
insert into estación (nombre, direccion) values ('Kuhlman-Cummerata', '083 Goodland Center');
insert into estación (nombre, direccion) values ('Herzog, Bednar and Stokes', '751 6th Plaza');
insert into estación (nombre, direccion) values ('Koelpin-Mayert', '9209 Debs Avenue');
insert into estación (nombre, direccion) values ('Kutch, DuBuque and Kutch', '76373 Susan Plaza');
insert into estación (nombre, direccion) values ('Turcotte, Green and Harvey', '86 Memorial Park');
insert into estación (nombre, direccion) values ('Cormier, Goldner and Sporer', '50 Rockefeller Terrace');
insert into estación (nombre, direccion) values ('Ortiz Inc', '6 Commercial Trail');
insert into estación (nombre, direccion) values ('Von Group', '79966 Wayridge Pass');
insert into estación (nombre, direccion) values ('O''Kon, Murazik and Cremin', '4 Parkside Terrace');
insert into estación (nombre, direccion) values ('Kub, Jacobi and Crona', '7902 Schlimgen Terrace');
insert into estación (nombre, direccion) values ('Renner-Macejkovic', '9612 South Crossing');
insert into estación (nombre, direccion) values ('Schamberger-Steuber', '3 La Follette Lane');
insert into estación (nombre, direccion) values ('Hartmann and Sons', '51 Crescent Oaks Lane');
insert into estación (nombre, direccion) values ('Marvin, Pouros and Shields', '5539 Hovde Drive');
insert into estación (nombre, direccion) values ('Kreiger-D''Amore', '9706 Del Sol Plaza');
insert into estación (nombre, direccion) values ('Schaefer-Nader', '006 Waubesa Center');
insert into estación (nombre, direccion) values ('Mitchell Inc', '360 Thackeray Terrace');
insert into estación (nombre, direccion) values ('Kertzmann, Powlowski and Heathcote', '47 Nevada Trail');
insert into estación (nombre, direccion) values ('Prohaska-Schaefer', '72 Loeprich Lane');
insert into estación (nombre, direccion) values ('Friesen, Legros and Schoen', '101 Calypso Lane');
insert into estación (nombre, direccion) values ('Lueilwitz, Lemke and Braun', '690 Comanche Avenue');
insert into estación (nombre, direccion) values ('Zemlak LLC', '31421 Texas Parkway');
insert into estación (nombre, direccion) values ('Lebsack-Bogisich', '5 Ridge Oak Terrace');
insert into estación (nombre, direccion) values ('Morar, Lebsack and Bashirian', '05465 Crownhardt Crossing');
insert into estación (nombre, direccion) values ('Pfannerstill Inc', '9 Hooker Lane');
insert into estación (nombre, direccion) values ('Bergstrom LLC', '46291 Jackson Place');
insert into estación (nombre, direccion) values ('Fritsch Group', '94 Acker Way');
insert into estación (nombre, direccion) values ('Howell, Cartwright and Kuphal', '42 Walton Junction');
insert into estación (nombre, direccion) values ('McClure-Maggio', '0 Kedzie Road');
insert into estación (nombre, direccion) values ('Okuneva-Russel', '47 Cascade Lane');
insert into estación (nombre, direccion) values ('Ankunding Group', '81 Northwestern Point');
insert into estación (nombre, direccion) values ('Nikolaus, Lehner and Braun', '6 Sachs Hill');
insert into estación (nombre, direccion) values ('Buckridge LLC', '4365 Aberg Lane');
insert into estación (nombre, direccion) values ('Lehner, Watsica and Osinski', '4881 Lawn Parkway');
insert into estación (nombre, direccion) values ('Kuhic-Mills', '68 Doe Crossing Way');
insert into estación (nombre, direccion) values ('Abshire-Langworth', '22 Gale Point');
insert into estación (nombre, direccion) values ('Shields, Goyette and Morar', '50792 Morningstar Circle');
insert into estación (nombre, direccion) values ('Dibbert and Sons', '526 Schlimgen Parkway');
insert into estación (nombre, direccion) values ('Auer-Herzog', '8933 Schmedeman Avenue');
insert into estación (nombre, direccion) values ('Tremblay-Jakubowski', '514 Maple Hill');
insert into estación (nombre, direccion) values ('Schiller, Terry and Fadel', '9333 Kenwood Avenue');
insert into estación (nombre, direccion) values ('Grady Inc', '4187 Paget Center');
insert into estación (nombre, direccion) values ('Schuppe, Tromp and Emmerich', '8913 Waywood Drive');
insert into estación (nombre, direccion) values ('Kirlin and Sons', '3 Division Center');
insert into estación (nombre, direccion) values ('McLaughlin, Zemlak and Cremin', '577 Johnson Pass');
insert into estación (nombre, direccion) values ('MacGyver-Ankunding', '07 Autumn Leaf Drive');
insert into estación (nombre, direccion) values ('Yundt, Bradtke and Maggio', '7 Little Fleur Parkway');
insert into estación (nombre, direccion) values ('Kunde-Wyman', '934 Upham Terrace');
insert into estación (nombre, direccion) values ('Okuneva LLC', '3 Sugar Road');
insert into estación (nombre, direccion) values ('Gusikowski-Schimmel', '3 Debs Center');
insert into estación (nombre, direccion) values ('Grady, Langworth and Fay', '5600 Eliot Center');
insert into estación (nombre, direccion) values ('Murazik-Kessler', '69199 Ridgeview Way');
