insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Packston Stebbins', 'Debs', '2009-05-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lorene Silbert', 'Golf View', '2017-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ebonee Pally', 'Blackbird', '2020-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fabio Potapczuk', 'Katie', '2011-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clemmy Barthelet', '8th', '2014-09-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gregg Buckley', 'Crowley', '2002-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karlen Learned', 'Judy', '2019-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gardener Colegate', 'Sutteridge', '2017-02-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Inger Vasyutochkin', 'Lyons', '2002-02-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vitia Iwanczyk', 'John Wall', '2021-05-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Terry Alabone', '6th', '2002-01-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sheffie Garstan', 'Chive', '2006-08-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marja Maleney', 'Sachtjen', '2019-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kingsly Scala', 'Anniversary', '2014-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Uta Mulliner', 'Brickson Park', '2017-05-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nessie Lorman', 'Sutherland', '2009-07-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Greta Sillitoe', 'Beilfuss', '2001-04-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kay Folbig', 'Kinsman', '2018-10-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jasmine Bernardet', 'Pine View', '2004-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Millie Predohl', 'Ridgeview', '2013-04-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chad Paintain', 'Florence', '2006-03-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Freeman Sever', 'Vahlen', '2003-12-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lynnell Petruska', 'Hanover', '2008-04-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jackqueline Anwyl', 'Paget', '2003-10-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Schuyler Dahlback', 'Welch', '2003-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gert Lusted', 'Mccormick', '2022-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christie Bauchop', 'Mariners Cove', '2004-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tammy Hadley', 'Fair Oaks', '2013-10-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hermann Rushmare', 'Clarendon', '2003-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Walton Silverwood', 'Blaine', '2012-04-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hugo Paskins', 'Hollow Ridge', '2021-02-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Russell Iggalden', 'Susan', '2013-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sharleen Laflin', 'Farmco', '2001-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rosie Lowing', 'Cascade', '2015-11-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kathye Seeborne', 'Village Green', '2003-01-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ahmed Truelock', 'Lakeland', '2020-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lissy Wyatt', 'Ludington', '2008-08-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kylie Amos', 'Scofield', '2011-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angelica Oag', 'Gina', '2006-08-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jamie Hamstead', 'Ridge Oak', '2021-04-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cristal Meader', 'Ludington', '2018-11-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arty Vann', 'Pennsylvania', '2005-02-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Konstantin Curl', 'La Follette', '2013-07-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Janela Walesby', 'Stuart', '2010-07-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Howey Dungay', 'Lakewood Gardens', '2004-07-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fran Cosley', 'Michigan', '2003-04-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Merrily Girodier', 'Bayside', '2022-08-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danna Uphill', 'Hazelcrest', '2006-10-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wright Mabbott', 'Ronald Regan', '2000-03-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gretna Nuzzetti', 'Fallview', '2011-12-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Benny Clucas', 'Maple Wood', '2020-11-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danya Tipper', 'Corry', '2003-05-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Melosa Truelove', 'Arizona', '2002-05-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corrie Skeemer', 'Oak Valley', '2006-11-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dinnie MacNulty', 'Kim', '2005-12-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Colly Kix', 'Shopko', '2018-08-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marvin Archibold', 'Lindbergh', '2019-11-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donica Beardon', 'Park Meadow', '2014-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Arden Polycote', 'Nevada', '2001-01-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elmira Hanselmann', 'Knutson', '2002-06-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Edita Nel', 'Shoshone', '2019-04-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elicia Toffalo', 'Northland', '2007-01-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Alair Itzkov', 'Arizona', '2016-01-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Imojean Casterton', 'Browning', '2023-09-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jabez Beevers', 'Kensington', '2003-10-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Amby Dudley', 'Portage', '2018-06-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shepard Diment', 'Straubel', '2016-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leonore Grammer', 'Nelson', '2023-11-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cherey Lyal', 'Melody', '2016-03-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('York Matisse', 'Schurz', '2014-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dniren Klehyn', 'Northridge', '2007-09-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nancy Littleton', 'Buena Vista', '2012-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clarine Snoxell', 'Ronald Regan', '2000-09-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tuesday Asquith', 'Barnett', '2008-07-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Katalin Bennedsen', 'Bellgrove', '2004-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garnette Ducker', 'Lighthouse Bay', '2004-01-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rozanne Swait', 'Kipling', '2016-02-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gradeigh Parell', 'Summer Ridge', '2018-05-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bordy Grishenkov', 'Corben', '2011-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nadiya Swaffield', 'Welch', '2014-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cristine Ferencz', 'Bunting', '2016-10-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('King Phizacklea', 'Graceland', '2015-12-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kasper Belch', '2nd', '2007-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cordy Pavel', 'Anderson', '2017-12-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Richmound Balden', 'Hollow Ridge', '2001-12-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mayne Pawlata', '3rd', '2017-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tadeo Heyball', 'Autumn Leaf', '2018-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Humfried Barthelet', 'Magdeline', '2011-07-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lola Tansley', 'Walton', '2022-06-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Odelia Elland', 'Amoth', '2020-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Norton McCritchie', 'Vahlen', '2003-09-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Garey Johannesson', 'Lighthouse Bay', '2010-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dacia Keslake', 'Waywood', '2013-05-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thomasin Cheake', 'American', '2014-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Les Abdon', 'Hauk', '2016-10-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Scottie Blabber', 'Northridge', '2005-07-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lizzy Nabarro', 'Crownhardt', '2001-10-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Betteann L''oiseau', 'Ridge Oak', '2018-12-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Annalee Erdis', 'Shoshone', '2023-07-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sissie Wilcock', 'Meadow Valley', '2006-10-20');
