insert into tren (modelo, capacidad) values ('Sonata', 1);
insert into tren (modelo, capacidad) values ('300', 2);
insert into tren (modelo, capacidad) values ('R-Class', 3);
insert into tren (modelo, capacidad) values ('M3', 4);
insert into tren (modelo, capacidad) values ('A3', 5);
insert into tren (modelo, capacidad) values ('Cherokee', 6);
insert into tren (modelo, capacidad) values ('Viper RT/10', 7);
insert into tren (modelo, capacidad) values ('Mirage', 8);
insert into tren (modelo, capacidad) values ('XK Series', 9);
insert into tren (modelo, capacidad) values ('4Runner', 10);
insert into tren (modelo, capacidad) values ('500SL', 11);
insert into tren (modelo, capacidad) values ('XC70', 12);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 13);
insert into tren (modelo, capacidad) values ('323', 14);
insert into tren (modelo, capacidad) values ('Talon', 15);
insert into tren (modelo, capacidad) values ('Accent', 16);
insert into tren (modelo, capacidad) values ('1500', 17);
insert into tren (modelo, capacidad) values ('Sorento', 18);
insert into tren (modelo, capacidad) values ('Escalade EXT', 19);
insert into tren (modelo, capacidad) values ('Galant', 20);
insert into tren (modelo, capacidad) values ('SL-Class', 21);
insert into tren (modelo, capacidad) values ('Justy', 22);
insert into tren (modelo, capacidad) values ('Pathfinder', 23);
insert into tren (modelo, capacidad) values ('Corolla', 24);
insert into tren (modelo, capacidad) values ('Forte', 25);
insert into tren (modelo, capacidad) values ('Crown Victoria', 26);
insert into tren (modelo, capacidad) values ('626', 27);
insert into tren (modelo, capacidad) values ('Silverado 3500', 28);
insert into tren (modelo, capacidad) values ('Aveo', 29);
insert into tren (modelo, capacidad) values ('7 Series', 30);
insert into tren (modelo, capacidad) values ('9000', 31);
insert into tren (modelo, capacidad) values ('Eclipse', 32);
insert into tren (modelo, capacidad) values ('Riviera', 33);
insert into tren (modelo, capacidad) values ('S70', 34);
insert into tren (modelo, capacidad) values ('Town Car', 35);
insert into tren (modelo, capacidad) values ('Tahoe', 36);
insert into tren (modelo, capacidad) values ('SLS AMG', 37);
insert into tren (modelo, capacidad) values ('Explorer Sport', 38);
insert into tren (modelo, capacidad) values ('Sonoma', 39);
insert into tren (modelo, capacidad) values ('960', 40);
insert into tren (modelo, capacidad) values ('Lynx', 41);
insert into tren (modelo, capacidad) values ('NSX', 42);
insert into tren (modelo, capacidad) values ('Electra', 43);
insert into tren (modelo, capacidad) values ('CL-Class', 44);
insert into tren (modelo, capacidad) values ('E150', 45);
insert into tren (modelo, capacidad) values ('Quattroporte', 46);
insert into tren (modelo, capacidad) values ('Park Avenue', 47);
insert into tren (modelo, capacidad) values ('Grand Voyager', 48);
insert into tren (modelo, capacidad) values ('G35', 49);
insert into tren (modelo, capacidad) values ('Gallardo', 50);
insert into tren (modelo, capacidad) values ('200', 51);
insert into tren (modelo, capacidad) values ('Fiero', 52);
insert into tren (modelo, capacidad) values ('Equus', 53);
insert into tren (modelo, capacidad) values ('Ram 1500', 54);
insert into tren (modelo, capacidad) values ('G', 55);
insert into tren (modelo, capacidad) values ('Pacifica', 56);
insert into tren (modelo, capacidad) values ('MGB', 57);
insert into tren (modelo, capacidad) values ('E150', 58);
insert into tren (modelo, capacidad) values ('Quattro', 59);
insert into tren (modelo, capacidad) values ('Rally Wagon 3500', 60);
insert into tren (modelo, capacidad) values ('Premier', 61);
insert into tren (modelo, capacidad) values ('Sorento', 62);
insert into tren (modelo, capacidad) values ('Truck', 63);
insert into tren (modelo, capacidad) values ('960', 64);
insert into tren (modelo, capacidad) values ('Sequoia', 65);
insert into tren (modelo, capacidad) values ('Reatta', 66);
insert into tren (modelo, capacidad) values ('Q5', 67);
insert into tren (modelo, capacidad) values ('S-Class', 68);
insert into tren (modelo, capacidad) values ('Prizm', 69);
insert into tren (modelo, capacidad) values ('DB9', 70);
insert into tren (modelo, capacidad) values ('TL', 71);
insert into tren (modelo, capacidad) values ('RSX', 72);
insert into tren (modelo, capacidad) values ('Prelude', 73);
insert into tren (modelo, capacidad) values ('Sebring', 74);
insert into tren (modelo, capacidad) values ('Tempo', 75);
insert into tren (modelo, capacidad) values ('Sunbird', 76);
insert into tren (modelo, capacidad) values ('Coachbuilder', 77);
insert into tren (modelo, capacidad) values ('Sebring', 78);
insert into tren (modelo, capacidad) values ('Crown Victoria', 79);
insert into tren (modelo, capacidad) values ('A4', 80);
insert into tren (modelo, capacidad) values ('Escalade ESV', 81);
insert into tren (modelo, capacidad) values ('57', 82);
insert into tren (modelo, capacidad) values ('Wrangler', 83);
insert into tren (modelo, capacidad) values ('Savana 2500', 84);
insert into tren (modelo, capacidad) values ('Grand Prix', 85);
insert into tren (modelo, capacidad) values ('400E', 86);
insert into tren (modelo, capacidad) values ('7 Series', 87);
insert into tren (modelo, capacidad) values ('Lancer Evolution', 88);
insert into tren (modelo, capacidad) values ('Sable', 89);
insert into tren (modelo, capacidad) values ('Dakota', 90);
insert into tren (modelo, capacidad) values ('Bonneville', 91);
insert into tren (modelo, capacidad) values ('Wrangler', 92);
insert into tren (modelo, capacidad) values ('Prizm', 93);
insert into tren (modelo, capacidad) values ('Suburban 1500', 94);
insert into tren (modelo, capacidad) values ('Mountaineer', 95);
insert into tren (modelo, capacidad) values ('Starion', 96);
insert into tren (modelo, capacidad) values ('Solara', 97);
insert into tren (modelo, capacidad) values ('Azera', 98);
insert into tren (modelo, capacidad) values ('E-Series', 99);
insert into tren (modelo, capacidad) values ('Durango', 100);
